const genText = document.getElementById("gen-text")

genText.addEventListener("click", function() {
  let messages = [
    "Eu amo você, eu amo muito você e vou te amar para sempre!",
    "Meu amor por vocês vai além do tempo.",
    "Sem você, eu não estou completo.",
    "Estou sempre pensando em você.",
    "Eu amo você.",
    "Somos perfeitos um para o outro.",
    "Eu não consigo mais viver sem você.",
    "Eu amo seus olhos.",
    "Eu amo ver você sorrir.",
    "Você me faz sorrir.",
    "Um dia de cada vez.",
    "Mal posso esperar para abraçar você.",
    "Estou sempre ansioso pra te ver.",
    "Você me completa.",
    "Você é a metade da minha laranja.",
    "Estou torcendo por nós.",
    "Você me faz ser uma pessoa melhor.",
    "Eu encontrei o amor quando te conheci.",
    "Eu penso em você o tempo todo.",
    "Você me inspira.",
    "Seja minha.",
    "Você faz meu coração derreter.",
    "Seja sincera consigo mesma!",
    "Você tem o meu coração, mantenha ele seguro.",
    "Você é o meu mundo!",
    "Eu amo você mais do que ontem!",
    "Seu amor é tudo que eu preciso.",
    "Agradeço sempre por ter você.",
    "Eu te amo até a lua e até a volta.",
    "Buques são flores mortas, num lindo arranjo feito para você",
    "Sem arrependimentos, apenas amor.",
    "Meus sonhos se tornam reais com você.",
    "Pra mim você é perfeita.",
    "Você é perfeita.",
    "You are the only exception.",
    "Eu sempre vou te amar.",
    "Eu vou te amar para sempre.",
    "Eu preciso de você hoje, amanhã e para sempre.",
    "Eu me apaixonei muitas vezes. E todas foram por você!",
    "Se me pagassem pra te amar, eu seria milionário.",
    "Eu vou te amar até o ultimo suspiro, porque não existe vida sem você.",
    "Quanto mais os dias passsam, mais eu me encanto por você.",
    "Eu sou seu fã número UM!",
    "Se você me perguntar quando quero estar com você, minha resposta será agora e para sempre.",
    "Para mim, estar com você é estar em casa.",
    "Queria estar sempre cuidando de você.",
    "Você chama de brega, eu chamo de amor!",
    "Meu amor por você não pode ser mensurado.",
    "Você é incrível.",
    "Você é radiante.",
    "NVocê brilha. De todas as cores.",
    "Se você não existisse, eu reiventaria você para que eu pudesse te amar.",
    "Você é preciosa.",
    "Me sinto abençoado por ter você.",
    "É angustiante ficar longe de você.",
    "É sempre melhor quando estamos juntos.",
    "Eu preciso de você como um coração precisa de sangue.",
    "Você é o motivo do meu sorriso.",
    "Eu queria dizer o quanto eu te amo, mas não existem palavras para isso.",
    "Todos os seus detalhes são encantadores.",
    "Eu e você somos como jazz e blues.",
    "O mundo é muito pequeno comparado ao meu amor por você.",
    "Mau posso esperar para te ver.",
    "Queria que você se amasse como eu te amo.",
    "Eu gosto de você.",
    "Sinto sua falta.",
    "Você sabe por quem eu estou apaixonado?Leia a primeira palavra novamente.",
    "Eu absolutamente adoro você.",
    "Suas fotos bobas fazem o meu dia melhor.",
    "Você está presente nos meus sonhos.",
    "Você me faz a pessoa mais feliz da terra.",
    "Sinto borboletas no estômago quando olho para você.",
    "Eu amo cada um dos seus detalhes.",
    "Eu amo o quão grande seus olhos são.",
    "Eu amo a sua voz.",
    "Eu amo o seu nariz.",
    "Eu amo o seu cabelo.",
    "Eu sou muito sortudo por você ser minha.",
    "Quer saber de algo? Eu te amo.",
    "Eu amo suas bochechas.",
    "Eu amo a maneira que você fica animada quando está fazendo o que gosta.",
    "Eu amo o seu sorriso envergonhado.",
    "Não consigo imaginar uma vida sem você.",
    "Dançaria comigo num dia chuvoso, despreocupados com todas as coisas?",
    "Não consigo imaginar o que seria minha felicidade sem você.",
    "Eu amo você como eu amo meus jogos.",
    "Você é uma gatinha.",
    "Você é a minha gatinha.",
    "Eu amo os seus lábios.",
    "Você é tão linda que não existe palavra ou existência que descreva sua beleza.",
    "Do sol até a lua. Eu te amo.",
    "Cada célula, átomo e molecula do meu corpo ama você.",
    "Somos eu e você contra o mundo.",
    "Meu amor por você é como o oceano, nunca acaba.",
    "Eu queria ser seu olá preferido e ser adeus mais doloroso. ",
    "Tenho muitas razões para morrer, mas se tenho uma para viver, é você!",
    "Você roubou meu coração e espero que nunca devolva!",
    "Você soa para mim como as poesias mais encatadoras.",
    "Você é amada.",
    "Você é minha para sempre. E eu seu para sempre.",
    "Se existisse um gênio dos desejos, eu desejaria você para sempre.",
    "Você é absolutamente explendida.",
    "Você trouxe a alegria pra minha vida."
  ]
  const textEl = document.querySelector(".textMessage")
  textEl.textContent = messages[Math.floor( Math.random()*messages.length )]
})